### ISSUE TITLE
Support for wikibase instances

### ISSUE THREAD

**Issue by labra** [weso/wikishape#12]
Wikishape started as a project with hard-coded support for Wikidata. However, we are more and more separating that behaviour to allow support for other wikibase instances.

- In settings, it is possible to change the endpoint to use a different wikibase endpoint

However, there are other features that still need to be fully checked to work with other wikibase instances.

**Comment by ulitol97** [comment]
Can you be more specific or give any tip on this? I can begin working on it.

**Comment by ulitol97** [comment]
With the changes in the back-end (https://github.com/weso/rdfshape-api/pull/299) and front-end (#42), users are able to use any Wikibase instance, with a couple of caveats:
- There's no golden rule to guess the SPARQL endpoint URL of a Wikibase, so users must know the base URL of their Wikibase instance and its SPARQL endpoint URL and pass them to the client. Otherwise, connection errors will occur.
![image](https://user-images.githubusercontent.com/35763574/158788279-2c294dc9-2f2c-492a-b411-4e1bc8ef26c9.png)

- There's no tool in MediaWiki's API that allows to fetch the schemas of a Wikibase. That's why Wikidata schemas are still hard-coded (#10) and the [Schema Info tool](https://wikishape.weso.es/schema) is the only one still limited to Wikidata.

For all other use cases, any Wikibase instance may be used and future problems can be addressed in other issues 🚀
